### ISSUE TITLE
🚀  Release 2.2.4

### ISSUE THREAD

**Issue by clotairer** [202ecommerce/ebay2#1]
This issue tracks the status of the Ebay 2 Official module release 2.2.4 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 2.2.4
Estimated beta | July 2022
Estimated release | July 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] Improve compatibility with PHP 5.6 (PS 1.6.0 and PS 1.6.1) [#34009]
    - [x] Sort the orders list from the most recent [#32265]
    - [x] Show not imported orders in a new list [#32394]
    - [x] Improve translations in onboarding setup [#33513]
    - [x] Add logger system for new APIs [#34052]
    - [x] Added a link to the PrestaShop order in the list of eBay orders [#32607]
    - [x] Added link to PrestaShop product in eBay "list of rejected products" [#32610]
    - [x] Rename "Onboarding URL" field in the token configuration section [#33413]
    - [x] Change field name in the "Orders not imported" tab [#34392]
    - [x] Login request after token generation [#35475]
    - [x] Show listings by shop in the eBay product list [#35616]
    - [x] Removed statistics [#35505]
    - [x] Removed links to help 202 in the module [#35530]
- [x] BugFix
    - [x] Error in importing orders when using multiple profiles [#34179]
    - [x] The token is not generated after onboarding configuration [#33563]
    - [x] Error after update shipping business policy [#34033]
    - [x] Invalid Shipping policy problem [#34229]
    - [x] PHP error message after installation (PS 1.6.0 and PS 1.6.1) [#33947]
    - [x] Error messages when installing on PS 1.6 [#34283]
    - [x] Correction of Auth accpeted URL provided when onboarding on PS 1.6 [#34227]
    - [x] Error during OAauth2 token generation in PS 1.6 [#34043]
    - [x] Error in the namespace of the vendor libs (PHP 5.6) [#34034]
    - [x] Link to eBay profile in the top bar doesn't work on PS 1.7 [#34125]
    - [x] idsite US et UK [#34722]
    - [x] Policy synchronisation error when the condition name is too long or when there are too many conditions [#35082]
    - [x] error message when uninstalling after module reset [#35615]
    - [x] Fix PrestaShop validator errors [#34796]
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - July 22
- [x] QA validation (Beta)
- [x] Release (Beta)
- [x] Final release
